# fly.toml app configuration file generated for empty-river-8206 on 2023-09-07T23:17:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-river-8206"
primary_region = "hkg"

[env]
  A = "{{A}}369"

[build]
  image = "registry.fly.io/empty-river-8206:latest"


[http_service]
  internal_port = {{port}}
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
