name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      -
        name: Authenticate to push our image to Fly
        run : flyctl auth docker -t=$FLY_API_TOKEN
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.fly.io/empty-river-8206:latest
      - 
        name: Replace env variables
        run: |
          sed -i "s/{{port}}/$PORT/g" fly.toml
          sed -i "s/{{A}}/$A/g" fly.toml
        env:
          PORT: ${{ vars.PORT }}
          A: ${{ vars.A }}
      - 
        name: Deploy to Fly.io
        run: flyctl deploy
